name: keyhole_manager
description: A simple Flame game.
version: 0.1.0

publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flame: 1.35.1
  flame_audio: 2.11.14
  flame_bloc: 1.12.21
  flutter:
    sdk: flutter
  gamepads: ^0.1.9

dev_dependencies:
  flame_lint: 1.4.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: false